server:
  port: ${PORT:10000}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:3306/alumind_feedbacks?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

openai_api_key: ${OPENAI_API_KEY}
